server:
  port: 8000

spring:
  profiles.active: prod
  datasource:
    name: employee_car_rental_db
    url: jdbc:postgresql://localhost:5430/employee_car_rental_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:/initial-data/initial_data.sql
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create-drop
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/

# Holiday Calendar
holiday-calendar:
  permanent-holidays:
    -
      day: 1
      month: 1
    -
      day: 6
      month: 1
    -
      day: 1
      month: 3
    -
      day: 3
      month: 3
    -
      day: 15
      month: 8
    -
      day: 1
      month: 11
    -
      day: 11
      month: 11
    -
      day: 25
      month: 12
    -
      day: 26
      month: 12

# Logging
logging:
  level:
    root: info
  file:
    name: ./logs/ecr-services.log
    max-size: 10MB