server:
  port: 8000

spring:
  profiles.active: prod
  datasource:
    name: employee_car_rental_db
    url: jdbc:postgresql://localhost:5430/employee_car_rental_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:/initial-data/initial_data.sql
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create-drop
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/


# Logging
logging:
  level:
    root: info
  file:
    name: ecr-services.log
    max-size: 10MB